AWSTemplateFormatVersion: 2010-09-09

Resources:
  ConfigRule:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: config.yaml

  Remediation:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        CheckForDefaultEncryptedVolumes: !GetAtt [ConfigRule, Outputs.EBSDefaultEncryptionRule]
      TemplateURL: remediation.yaml